'\" t
.\"     Title: json-glib-format
.\"    Author: Emmanuele Bassi
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 03/18/2017
.\"    Manual: User Commands
.\"    Source: JSON-GLib
.\"  Language: English
.\"
.TH "JSON\-GLIB\-FORMAT" "1" "" "JSON-GLib" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
json-glib-format \- JSON\-GLib formatting tool
.SH "SYNOPSIS"
.HP \w'\fBjson\-glib\-format\fR\ 'u
\fBjson\-glib\-format\fR [\fB\-h\fR,\ \fB\-\-help\fR] [\fB\-\-prettify\fR] [\fB\-\-indent\-spaces\fR\ \fISPACES\fR] URI [URI...]
.SH "DESCRIPTION"
.PP
\fBjson\-glib\-format\fR
offers a simple command line interface to format JSON data\&. It reads a list or URIs, applies the spacified formatting rules on the JSON data, and outputs the formatted JSON to the standard output\&.
.PP
The resources to operate on are specified by the
\fIURI\fR
argument\&.
.SH "COMMANDS"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Prints help and exits\&.
.RE
.PP
\fB\-p\fR, \fB\-\-prettify\fR
.RS 4
Prettifies the output, by adding spaces and indentation\&. This argument is useful to improve the readability of JSON data, at the expense of its size\&.
.RE
.PP
\fB\-\-indent\-spaces\fR \fISPACES\fR
.RS 4
Changes the number of spaces using to indent the JSON data from the default of 2\&. This argument is only considered if
\fB\-\-prettify\fR
is used\&.
.RE
