'\" t
.\"     Title: json-glib-validate
.\"    Author: Emmanuele Bassi
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 03/18/2017
.\"    Manual: User Commands
.\"    Source: JSON-GLib
.\"  Language: English
.\"
.TH "JSON\-GLIB\-VALIDATE" "1" "" "JSON-GLib" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
json-glib-validate \- JSON\-GLib validation tool
.SH "SYNOPSIS"
.HP \w'\fBjson\-glib\-validate\fR\ 'u
\fBjson\-glib\-validate\fR [\fB\-h\fR,\ \fB\-\-help\fR] URI [URI...]
.SH "DESCRIPTION"
.PP
\fBjson\-glib\-validate\fR
offers a simple command line interface to validate JSON data\&. It lets you list URIs that point to JSON data and checks that the data conforms to the JSON syntax\&.
.PP
The resources to operate on are specified by the
\fIURI\fR
argument\&.
.PP
If the JSON data is valid,
\fBjson\-glib\-validate\fR
will terminate with an exit code of 0; if the data is invalid, an error will be printed on
\fIstderr\fR
and
\fBjson\-glib\-validate\fR
will terminate with a nonzero exit code\&.
.SH "COMMANDS"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Prints help and exits\&.
.RE
